In [130]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import matplotlib.patches as mpatches

In [131]:
# importing the letters dataset
letter = pd.read_csv("C://Users//dsouz//Desktop//ALY6020//letters.csv")

In [132]:
letter_new = letter

In [133]:
letter_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Data columns (total 46 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   label     42000 non-null  int64
 1   pixel43   42000 non-null  int64
 2   pixel44   42000 non-null  int64
 3   pixel92   42000 non-null  int64
 4   pixel124  42000 non-null  int64
 5   pixel125  42000 non-null  int64
 6   pixel126  42000 non-null  int64
 7   pixel127  42000 non-null  int64
 8   pixel128  42000 non-null  int64
 9   pixel129  42000 non-null  int64
 10  pixel130  42000 non-null  int64
 11  pixel131  42000 non-null  int64
 12  pixel132  42000 non-null  int64
 13  pixel133  42000 non-null  int64
 14  pixel134  42000 non-null  int64
 15  pixel135  42000 non-null  int64
 16  pixel136  42000 non-null  int64
 17  pixel137  42000 non-null  int64
 18  pixel138  42000 non-null  int64
 19  pixel146  42000 non-null  int64
 20  pixel147  42000 non-null  int64
 21  pixel148  42000 non-null  int64
 22

In [134]:
letter_new.shape

(42000, 46)

In [135]:
X = letter_new.iloc[:,:-1].values
y = letter_new.iloc[:,:1].values

# Data Sampling

In [136]:
#Splitting the data into train and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

# KNN

In [163]:
#Import knearest neighbors Classifier model
from sklearn.neighbors import KNeighborsClassifier

In [164]:
#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=5)

In [165]:
#Train the model using the training sets
knn.fit(X_train, y_train)

C:\Users\dsouz\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:200: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [166]:
#Predict the response for test dataset
y_pred = knn.predict(X_test)

In [167]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.665952380952381


In [168]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[1142    1   30    6   14    8   29   12    7   11]
 [   0 1341    7    8    8    4    6    3   15    2]
 [  72   45  819  136   41   17   23   43   60   17]
 [  17   41  188  766   35   73   17   32  122   38]
 [  27   94   19   26  649   38   28  207   12   93]
 [  17   35   44  179   52  635   55   59   30   30]
 [  23   28   22   14   31   23 1076    1    9    0]
 [  12    8   14   27  105   45    0  828   29  228]
 [  24  120  126  211   29   53   32   40  596   39]
 [  22   13   23   31   80   31    0  456   27  539]]
              precision    recall  f1-score   support

           0       0.84      0.91      0.87      1260
           1       0.78      0.96      0.86      1394
           2       0.63      0.64      0.64      1273
           3       0.55      0.58      0.56      1329
           4       0.62      0.54      0.58      1193
           5       0.69      0.56      0.62      1136
           6       0.85      0.88      0.86      1227
           7       0.49      0.64   

In [169]:
knn.score(X_test, y_test)

0.665952380952381

In [170]:
#Regenerating model for K =7
#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=7)

In [171]:
#Train the model using the training sets
knn.fit(X_train, y_train)

C:\Users\dsouz\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:200: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=7)

In [172]:
#Predict the response for test dataset
y_pred = knn.predict(X_test)

In [173]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6669047619047619


In [174]:
#Regenerating model for K =4
#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=4)

In [175]:
#Train the model using the training sets
knn.fit(X_train, y_train)

C:\Users\dsouz\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:200: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=4)

In [176]:
#Predict the response for test dataset
y_pred = knn.predict(X_test)

In [177]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6596825396825396


# Neural Network model

In [184]:

import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# Import other necessary modules 
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [185]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(3,3,3), activation='relu', solver='adam', max_iter=500)
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

C:\Users\dsouz\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [186]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,predict_test))

[[1150    0   21    6   17    9   27   11    6   13]
 [   1 1339    6   11    9    4    7    1   14    2]
 [  81   48  824  113   35   16   21   36   72   27]
 [  27   43  207  746   33   67   20   27  124   35]
 [  30   99   25   27  649   36   22  196   13   96]
 [  22   35   44  184   51  623   60   45   34   38]
 [  33   30   19   16   39   23 1058    1    8    0]
 [  14   10   24   32   96   35    0  836   25  224]
 [  24  121  153  223   30   52   27   36  565   39]
 [  24   14   29   34   80   34    0  460   25  522]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1260
           1       1.00      1.00      1.00      1394
           2       1.00      1.00      1.00      1273
           3       1.00      1.00      1.00      1329
           4       1.00      1.00      1.00      1193
           5       1.00      1.00      1.00      1136
           6       0.49      1.00      0.66      1227
           7       0.99      0.96   

In [187]:
mlp.score(X_test, y_test)

0.8897619047619048

In [188]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_train,predict_train))

[[1150    0   21    6   17    9   27   11    6   13]
 [   1 1339    6   11    9    4    7    1   14    2]
 [  81   48  824  113   35   16   21   36   72   27]
 [  27   43  207  746   33   67   20   27  124   35]
 [  30   99   25   27  649   36   22  196   13   96]
 [  22   35   44  184   51  623   60   45   34   38]
 [  33   30   19   16   39   23 1058    1    8    0]
 [  14   10   24   32   96   35    0  836   25  224]
 [  24  121  153  223   30   52   27   36  565   39]
 [  24   14   29   34   80   34    0  460   25  522]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2872
           1       1.00      1.00      1.00      3290
           2       1.00      1.00      1.00      2904
           3       1.00      1.00      1.00      3022
           4       1.00      1.00      1.00      2879
           5       1.00      1.00      1.00      2659
           6       0.51      1.00      0.67      2910
           7       1.00      0.96   

In [189]:
mlp.score(X_train, y_train)

0.8948639455782313